apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neo4j-ingress
  namespace: neo4j
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
    - host: neo4j.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neo4j-http
                port:
                  number: 7474
